[book]
authors = ["Li Hongmin"]
language = "zh-CN"
multilingual = false
src = "src"
title = "跟太太一起理财"
description = "一本温暖的夫妻理财入门书"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/li-hongmin/financial-book-opensource"
git-repository-icon = "fa-github"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 0
